# Setup
title:        Awesome
tagline:      A responsive theme for your project on GitHub Pages
baseurl:      ""
paginate:     1
locale:       "en"

# About/contact
author:
  name:       Kahee
  url:        http://lgh7418.github.io

# Gems
gems:
  - jekyll-paginate

#Others
markdown: kramdown