# Setup
title:        My Coding
tagline:      프로그래밍 공부 기록
baseurl:      ""
paginate:     1
locale:       "en"

# About/contact
author:
  name:       Kahee
  url:        http://lgh7418.github.io

# Gems
plugins:
  - jekyll-paginate
  - jekyll-mermaid

#Others
markdown: kramdown

mermaid:
  src: 'path/to/mermaid.js'