# Setup
title:        Awesome
tagline:      프로그래밍 공부 기록
baseurl:      ""
paginate:     1
locale:       "en"

# About/contact
author:
  name:       Kahee
  url:        http://lgh7418.github.io

# Gems
gems:
  - jekyll-paginate

#Others
markdown: kramdown